spring:
  application:
    name: odc-file
  cache:
    type: redis
    redis:
      time-to-live: 86400000
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://122.51.145.136:30606/odc_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: odc
    password: 123456!QAZ
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 122.51.145.136
    port: 60379
    database: 1
    lettuce:
      shutdown-timeout: 30000
server:
  port: 8200
butterfly:
  resource:
    server:
      enable: false


