spring:
  application:
    name: odc-platform
  datasource:
    url: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: xxx
    password: xxx
  boot:
    admin:
      client:
        url: http://localhost:8768

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8030

odc:
  resource:
    server:
      enable: true
logging:
  level:
    org.dshubs.odc.infra.mapper: debug