spring:
  application:
    name: odc-oauth
  thymeleaf:
    cache: false
  datasource:
    url: xxx
    username: xxx
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost

  main:
    allow-bean-definition-overriding: true
server:
  port: 8010
  servlet:
    context-path: /oauth
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'



odc:
  oauth:
    redirect-url: ${BUTTERFLY_OAUTH_REDIRECT_URL:login}
  resource:
    server:
      enable: true
logging:
  level:
    org.dshubs.odc: debug